### ISSUE TITLE
NoClassDefFoundError: com/itextpdf/text/DocumentException

### ISSUE THREAD

**Issue by ylluminate** [danmbox/briss2#4]
After building `briss` and executing the application via:
`java -jar target/briss-*.jar /path/to/pdf.pdf`

I ran into the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/itextpdf/text/DocumentException
    at at.laborg.briss.Briss.main(Briss.java:59)
Caused by: java.lang.ClassNotFoundException: com.itextpdf.text.DocumentException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more
```

Any idea of what's happening here?

**Comment by ylluminate** [comment]
So I got to wondering and I unzip'd an archive and then executed that with success.

**Comment by zsxgb** [comment]
how to unzip file. @ylluminate
